feat: a11y-heading-in-sectioning-contentでSectioningContentと予想される名前だがそれらの拡張ではないコンポーネントはエラーとする
kufu/eslint-plugin-smarthr pull request #77
Opened 2023-09-05 08:36 UTC by AtsushiM

2023-09-08 00:31 UTC, misako0927 requested changes

2023-09-08 00:31 UTC, misako0927 commented on test/a11y-heading-in-sectioning-content.js
> +    { code: 'const StyledSection = styled.div``', errors: [ { message: `StyledSection は smarthr-ui/Section をextendすることを期待する名称になっています
[ask] テストケースにnavi、asideがないのは、sectionやarticleと形式が一緒だから省いた認識で良いでしょうか？

[imo]`^aside$`のパターンがなさそうなので、そちらは入れた方がいいかなと思いました

2023-09-08 00:31 UTC, misako0927 commented on rules/a11y-heading-in-sectioning-content/index.js
> +  '(A|^a)rticle$': [
[ask]ArticleXxxなどはチェックしていないと思うのですが、何か理由はあるのでしょうか？（あまりつけない名称だからでしょうか・・？）

2023-09-12 02:07 UTC, AtsushiM commented on test/a11y-heading-in-sectioning-content.js
> +    { code: 'const StyledSection = styled.div``', errors: [ { message: `StyledSection は smarthr-ui/Section をextendすることを期待する名称になっています
> テストケースにnavi、asideがないのは、sectionやarticleと形式が一緒だから省いた認識で良いでしょうか？
> ^aside$のパターンがなさそうなので、そちらは入れた方がいいかなと思いました

同じテストになってしまうし、ロジック的にasideだけコケる、とかは無いだろうからいいかな、と思っていましたが、一度もやらないのは微妙ですし入れちゃいます！

2023-09-12 02:10 UTC, AtsushiM commented on rules/a11y-heading-in-sectioning-content/index.js
> +  '(A|^a)rticle$': [
ArticleHeadingのような `ArticleではなくXxxxとして扱いたい` 場合がありえるため、判定が大変になってしまうからですね...
一応 `XxxxArticleAndYyyy` とか`HogeSectionWithFuga` とかはありえると思いますが、今のところ見かけたことがないため、必要になったら実装しようかと考えています

2023-09-12 06:51 UTC, misako0927 commented on rules/a11y-heading-in-sectioning-content/index.js
> +  '(A|^a)rticle$': [
承知しました！

2023-09-12 12:21 UTC, misako0927 commented on test/a11y-heading-in-sectioning-content.js
> +    { code: 'const StyledSection = styled.div``', errors: [ { message: `StyledSection は smarthr-ui/Section をextendすることを期待する名称になっています
確認しました！

2023-09-12 12:21 UTC, misako0927 approved these changes
LGTM!

2023-09-12 23:23 UTC, merged